# Generated by Django 3.0.2 on 2020-02-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorski', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmeti',
            name='kod',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
