# Generated by Django 3.0.2 on 2020-02-07 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorski', '0002_auto_20200203_0951'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='upisi',
            unique_together={('student', 'predmet')},
        ),
    ]
